### PR TITLE
Fixed C++ Qt integration support by changing reserved keyword "emit" to "transmit". Also changed the comments to reflect the change.

### PR DESCRIPTION
**Pull request by tryphe**
Hey there. Thanks for making such a great library! I can't seem to find anything that even comes close to being this good.

I had a tiny issue with Qt integration, since "emit" is a keyword within Qt, so I made a simple commit to resolve the issue.

Cheers.

### CODE REVIEW

**Comment by skeeto** [comment]
@tryphe: Nice catch, thanks! I don't know if "trasmit" quite captures
the same meaning as "emit" in this case, but "extrude" and "vomit" don't
really sound very good, and I suspect "yield" may have even more
technical problems than "emit."

@Kronuz: I hope you don't mind that I've accepted this change.

**Comment by tryphe** [comment]
@skeeto Rofl! You're right; "transmit" was the only thing I could think of, and a thesaurus wasn't a very good help. I was torn between renaming it or naming it to "emitData()", but went with the former. Feel free to change it the likes of "emitData()" or something similar, I won't be offended. :)

**Comment by Kronuz** [comment]
I'd prefer using `produce()` instead.

**Comment by tryphe** [comment]
@Kronuz, I agree. 

Made a new PR for it: a64d84a

**Pull request merged**
